pygments: true
permalink: /:title/
markdown: kramdown
exclude: ['.git']
title: "Developer's Delight"
description: "Shinyoung Choi with all the data in the world"
url: https://shinyoungashleychoi.github.io
paginate: 5
paginate_path: "/page:num/"
safe: false
plugins:
  - jekyll-paginate
