# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Shinyoung Choi
email: choishin0@gmail.com

#write html inside the double quotes to display in jumbotron
description: Developer's Delight



baseurl: "" # the subpath of your site, e.g. /blog
url: "http://shinyoungashleychoi.github.io" # the base hostname & protocol for your site
twitter_username:
github_username:  shinyoungashleychoi

# Build settings
markdown: kramdown
