pygments: true
permalink: /:title/
markdown: kramdown
exclude: ['.git']
title: "Developer's Delight"
description: "Shinyoung Choi with all the data in the world"
url: https://shinyoungashleychoi.github.io
