name: Deploy Jekyll to GitHub Pages

on:
  push:
    branches:
      - master  # 또는 배포할 브랜치

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.1'  # Jekyll 지원 최신 버전

      - name: Install dependencies
        run: |
          gem install bundler
          bundle install

      - name: Build Jekyll site (Run Plugins)
        run: bundle exec jekyll build --trace
        env:
          JEKYLL_ENV: production