name: Deploy Jekyll to GitHub Pages

on:
  push:
    branches:
      - master  # 또는 main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.1'

      - name: Install dependencies
        run: |
          gem install bundler
          bundle install

      - name: Build Jekyll site (Run Plugins)
        run: bundle exec jekyll build --trace
        env:
          JEKYLL_ENV: production

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}  # 여기서 GH_PAT 대신 GITHUB_TOKEN 사용
          publish_dir: ./_site
          publish_branch: gh-pages  # 배포할 브랜치 (default: gh-pages)
